services:
  - type: redis
    name: corruptintel-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction

  - type: web
    name: corruptintel-api
    runtime: docker
    dockerfilePath: ./infrastructure/docker/api.Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: AI_DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: corruptintel-redis
          property: connectionString
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRY
        value: 8h
      - key: LLM_PROVIDER
        value: anthropic
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://corruptintelke-web.vercel.app

  - type: worker
    name: corruptintel-worker
    runtime: docker
    dockerfilePath: ./infrastructure/docker/worker.Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: AI_DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: corruptintel-redis
          property: connectionString
      - key: LLM_PROVIDER
        value: anthropic
      - key: ANTHROPIC_API_KEY
        sync: false
