import { Router } from "express";
import { z } from "zod";
import { runQueryPlanner, runReportingAgent } from "@corruptintel/ai";
import {
  resolveCaseIdsFromFilters,
  assembleCaseContexts,
  buildReportingContext,
} from "../lib/researchRetrieval";

const router = Router();

const researchSchema = z.object({
  query: z.string().min(3),
});

/**
 * POST /research — grounded AI research brief. Read-only against the
 * published graph (AI Agent Architecture §4/§7): nothing in this handler
 * writes to any table. The pipeline is:
 *   1. Query Planner (LLM, schema-constrained) — natural language -> filters
 *   2. Deterministic SQL — filters -> matching published case ids
 *   3. Deterministic assembly — case ids -> claims/timeline/amounts/entities,
 *      each already carrying its evidence_id from the published schema
 *   4. Reporting Agent (LLM, schema-constrained) — retrieved claims ->
 *      key_findings + unknown_or_missing ONLY
 *   5. Mechanical validation — every key_finding's evidence_ids must be a
 *      subset of what was actually retrieved, or it's dropped
 * Timeline, financial exposure, entities, and sources are never touched by
 * an LLM — they're a direct, deterministic projection of published rows.
 */
router.post("/", async (req, res, next) => {
  try {
    const { query: userQuery } = researchSchema.parse(req.body);

    let filters;
    try {
      const planned = await runQueryPlanner(userQuery);
      filters = planned.filters;
    } catch (err) {
      res.status(503).json({
        error: {
          code: "LLM_UNAVAILABLE",
          message:
            "The research agent's query planner could not run (is ANTHROPIC_API_KEY set?). " +
            "No fallback narrative is generated — returning an error rather than guessing.",
        },
      });
      return;
    }

    const caseIds = await resolveCaseIdsFromFilters(filters);

    if (caseIds.length === 0) {
      res.json({
        data: {
          executive_summary: "No published cases matched this query.",
          key_findings: [],
          timeline: [],
          financial_exposure: [],
          entities: [],
          conflicting_accounts: [],
          case_status: "UNKNOWN_UNRESOLVED",
          unknown_or_missing: [
            "Insufficient evidence to establish this claim — no published case in the current dataset matches the query's filters.",
          ],
          sources: [],
        },
        evidence: [],
        meta: { filters, matched_cases: 0 },
      });
      return;
    }

    const contexts = await assembleCaseContexts(caseIds);
    const { claimsForReport, allEvidence, evidenceById } = await buildReportingContext(contexts);

    let reportOutput;
    try {
      const reported = await runReportingAgent(userQuery, claimsForReport);
      reportOutput = reported.output;
    } catch (err) {
      res.status(503).json({
        error: {
          code: "LLM_UNAVAILABLE",
          message: "The research agent's reporting step could not run. Matched cases and raw evidence are listed below without a synthesized summary.",
        },
        data: {
          executive_summary: `Matched ${contexts.length} published case(s); narrative synthesis unavailable.`,
          key_findings: [],
          timeline: [],
          financial_exposure: [],
          entities: [],
          conflicting_accounts: [],
          case_status: contexts.length === 1 ? contexts[0].current_status : "UNKNOWN_UNRESOLVED",
          unknown_or_missing: ["Narrative synthesis unavailable — reporting agent could not run."],
          sources: allEvidence,
        },
        evidence: allEvidence,
      });
      return;
    }

    // Mechanical grounding check: drop any finding citing an evidence_id we
    // did not actually retrieve. This mirrors the extraction pipeline's
    // evidenceLinker — a model's say-so is never sufficient on its own.
    const validEvidenceIds = new Set(allEvidence.map((e) => e.evidence_id));
    const verifiedFindings = reportOutput.key_findings.filter((f) => {
      const allValid = f.evidence_ids.length > 0 && f.evidence_ids.every((id) => validEvidenceIds.has(id));
      if (!allValid) {
        console.warn(
          `Dropped a reporting-agent finding citing unretrieved evidence_id(s): ${JSON.stringify(f.evidence_ids)}`
        );
      }
      return allValid;
    });

    // Deterministic timeline, financial exposure, entities — never generated by the model.
    const timeline = contexts.flatMap((ctx) =>
      ctx.timeline.map((t) => ({
        date: t.date,
        description: `${ctx.title}: status changed to ${t.status.replace(/_/g, " ")}${t.notes ? ` — ${t.notes}` : ""}`,
        evidence: t.evidence_id ? evidenceById.get(t.evidence_id) ?? null : null,
      }))
    );

    const financial_exposure = contexts.flatMap((ctx) =>
      ctx.financial_amounts.map((a) => ({
        amount: a.amount,
        currency: a.currency,
        amount_type: a.amount_type,
        is_approximate: a.is_approximate,
        context_note: `From case: ${ctx.title}`,
        evidence: evidenceById.get(a.evidence_id) ?? null,
      }))
    );

    const seenEntities = new Set<string>();
    const entities = contexts.flatMap((ctx) =>
      ctx.entities
        .filter((e) => {
          const key = `${e.entity_type}:${e.name}`;
          if (seenEntities.has(key)) return false;
          seenEntities.add(key);
          return true;
        })
        .map((e) => ({ name: e.name, type: e.entity_type as "PERSON" | "COMPANY" | "INSTITUTION", role: e.role || "" }))
    );

    const conflicting_accounts = contexts.flatMap((ctx) => {
      const byId = new Map(ctx.claims.map((c) => [c.id, c]));
      const pairs: { claim_a: unknown; claim_b: unknown }[] = [];
      for (const claim of ctx.claims) {
        if (claim.conflicts_with_claim_id && byId.has(claim.conflicts_with_claim_id)) {
          const other = byId.get(claim.conflicts_with_claim_id)!;
          pairs.push({
            claim_a: { id: claim.id, claim_text: claim.claim_text, certainty: claim.certainty, evidence: evidenceById.get(claim.evidence_id) ?? null },
            claim_b: { id: other.id, claim_text: other.claim_text, certainty: other.certainty, evidence: evidenceById.get(other.evidence_id) ?? null },
          });
        }
      }
      return pairs;
    });

    const executiveSummary =
      contexts.length === 1
        ? `Matched 1 published case: "${contexts[0].title}" (status: ${contexts[0].current_status.replace(/_/g, " ")}).`
        : `Matched ${contexts.length} published cases across statuses: ${Array.from(new Set(contexts.map((c) => c.current_status))).join(", ")}.`;

    res.json({
      data: {
        executive_summary: executiveSummary,
        key_findings: verifiedFindings,
        timeline,
        financial_exposure,
        entities,
        conflicting_accounts,
        case_status: contexts.length === 1 ? contexts[0].current_status : "UNKNOWN_UNRESOLVED",
        unknown_or_missing: reportOutput.unknown_or_missing,
        sources: allEvidence,
      },
      evidence: allEvidence,
      meta: { filters, matched_cases: contexts.length },
    });
  } catch (err) {
    next(err);
  }
});

export default router;
